
query ABOUT {
  about {
    pageTitle
    headerText
    skills {
      id
      title
      subSkills {
        ... on ComponentElementsListDetail {
          id
          name
        }
      }
    }
    imageProfil {
      id
      url
      alternativeText
      formats
    }
    experiencesList {
      ... on ComponentElementsExperience {
        id
        title
        subTitle
        description
        period {
          id
          startDate
          endDate
        }
      }
    }
    educations {
      ... on ComponentElementsEduction {
        id
        name
        location
        startDate
        endDate
      }
    }
  }
}
