query GLOBAL{
  global {
    siteName 
    contactEmail
    siteLanguage
    legals
    socialNetworks{
      id
      title
      url
      icon{
        url
        alternativeText
      }
    }
    logo {
      url
      alternativeText
    }
  }
}

