query PROJECT($slug: String!){
  projectBySlug(slug: $slug){
    id
    title
    description
    slug
    codeLink
    domain{
      id
      name
      link
    }
    cover{
      id
      url
      formats
      alternativeText
    }

    imagesCollection{
      id
      alternativeText
      url
      formats
    }
    categories{
      id
      title
    }
    }
  }